### PR TITLE
Fix compilation errors using Swift 5

### LINKED ISSUE #15: compression_stream calls only available on OS X 10.11 or newer
I just added DataCompression to a Swift 5 based SwiftPM tool [this one](https://github.com/JamitLabs/Accio) but I am now getting errors stating:

```bash
'compression_stream_init' is only available on OS X 10.11 or newer
'compression_stream_destroy' is only available on OS X 10.11 or newer
```

Here's my Package.swift file content:

```swift
// swift-tools-version:5.0

import PackageDescription

let package = Package(
    name: "Accio",
    platforms: [.macOS(.v10_12)],
    products: [
        .executable(name: "accio", targets: ["Accio"]),
        .library(name: "AccioKit", type: .dynamic, targets: ["AccioKit"])
    ],
    dependencies: [
        .package(url: "https://github.com/mw99/DataCompression.git", .upToNextMajor(from: "3.4.0")),
        .package(url: "https://github.com/Flinesoft/HandySwift.git", .upToNextMajor(from: "2.8.0")),
        .package(url: "https://github.com/onevcat/Rainbow.git", .upToNextMajor(from: "3.1.4")),
        .package(url: "https://github.com/jakeheis/SwiftCLI.git", .upToNextMajor(from: "5.2.2")),
        .package(url: "https://github.com/kareman/SwiftShell.git", .upToNextMajor(from: "4.1.2")),
        .package(url: "https://github.com/mengxiangyue/xcodeproj.git", .branch("master")), // TODO: switch back to original once https://github.com/tuist/xcodeproj/issues/385 is fixed
    ],
    targets: [
        .target(
            name: "Accio",
            dependencies: ["AccioKit"]
        ),
        .target(
            name: "AccioKit",
            dependencies: [
                "DataCompression",
                "HandySwift",
                "Rainbow",
                "SwiftCLI",
                "SwiftShell",
                "xcodeproj",
            ]
        ),
        .testTarget(
            name: "AccioKitTests",
            dependencies: ["AccioKit", "HandySwift", "xcodeproj"]
        )
    ]
)

```

### PR DESCRIPTION
**Pull request by Dschee**
This fixes #15. I tested it out and using my fork works fine.

### CODE REVIEW

**Comment by tonyarnold** [comment]
@mw99 any chance this could be merged in and a new release tagged? This PR allows DataCompression to be used via Xcode 11's SPM support.

**Comment by mw99** [comment]
Hi. I did kinda forget about this... sorry. Will test this and try to release it before Xcode 11 is released.

**Comment by tonyarnold** [comment]
No dramas - I understand how it works. Thanks for your work 😀

**Comment by mw99** [comment]
Fixed in version [**3.6.0**](https://github.com/mw99/DataCompression/releases/tag/3.6.0)
Thanks guys!

**Pull request closed without merging**
