### PR TITLE
Fixes for Swift 4.1 compatibility

### PR DESCRIPTION
**Pull request by oflasch**
see https://github.com/apple/swift-evolution/blob/master/proposals/0184-unsafe-pointers-add-missing.md

### CODE REVIEW

**Comment by mw99** [comment]
Thanks! Will be merge in the next release.

**Comment by omidontop** [comment]
I second the need for this PR! Thanks to both @oflasch and @mw99.

**Comment by mw99** [comment]
Yes that got a little bit late. Swift 4.1 compatibility and other extra updates will get released soon.

**Comment by mw99** [comment]
Thanks for waiting. Version 3.0.0 is out. With Swift 4.1 as well as gzip support. You may want to take a look at the [changelog](https://github.com/mw99/DataCompression#version-20x-to-300). Thanks for your feedback.

**Comment by omidontop** [comment]
Awesome! Thanks!

**Pull request closed without merging**
